### ISSUE TITLE
请问gateWay中AuthorizationManager这个类中权限判断为什么进不去

### ISSUE THREAD

**Issue by 294640262** [hxrui/youlai-mall#17]
使用的是admin账号，在执行到.any()时直接跳过，无法进入到里面的权限判断，请问这是什么原因呢？该怎么解决呢？
```
     Mono<AuthorizationDecision> authorizationDecisionMono = mono
                .filter(Authentication::isAuthenticated)
                .flatMapIterable(Authentication::getAuthorities)
                .map(GrantedAuthority::getAuthority)
                .any(roleId -> {
                    // roleId是请求用户的角色(格式:ROLE_{roleId})，authorities是请求资源所需要角色的集合
                    log.info("访问路径：{}", path);
                    log.info("用户角色信息：{}", roleId);
                    log.info("资源需要权限authorities：{}", authorities);
                    return authorities.contains(roleId);
                })
                .map(AuthorizationDecision::new)
                .defaultIfEmpty(new AuthorizationDecision(false));
```

**Comment by hxrui** [comment]
@294640262 
确认下面这两个问题：
1.解析JWT后看下authorities字段是否有角色id集合
2.看下权限角色规则是否正常加载到redis中

**Comment by 294640262** [comment]
`{
    "alg": "RS256",
    "typ": "JWT"
}
{
    "user_name": "admin",
    "scope": ["all"],
    "id": 2,
    "exp": 1613726519,
    "authorities": ["2"],
    "jti": "5d9c81c8-0627-43fe-8293-9f6f1b718763",
    "client_id": "youlai-admin"
}`
1、以上为解析出来的结果，其中authorities带有角色id
2、权限角色规则是有存到redis中的，在进入.any()方法前，获取到的ahthorities为["ROLE_1","ROLE_2"]
还有其他可能的原因吗？代码我是直接跑起来的，没做改动

**Comment by hxrui** [comment]
@294640262 刚才线上环境被人改权限数据了，导致菜单模块无法访问，你现在再试试

**Comment by hxrui** [comment]
@294640262 稍等你这个数据没问题

**Comment by hxrui** [comment]
@294640262 没做改动怎么会有user_name

**Comment by 294640262** [comment]
这个可能是比较早之前拉的版本，刚才重新在gitee上拉了个最新的版本，也是同样的问题

**Comment by hxrui** [comment]
@294640262 github和gitee是同步的，我试了启动也没问题，线上的也ok，群里的小伙伴也没这个问题

**Comment by hxrui** [comment]
@294640262 试着把maven仓库清理下
