### ISSUE TITLE
小程序会员没有RBAC设定吗

### ISSUE THREAD

**Issue by spatack** [hxrui/youlai-mall#20]
在User的构造方法`User(AuthMemberDTO member)`中，不进行authorities的添加，那么在生成token是不包含 role id的吧。

**Comment by hxrui** [comment]
@spatack 是的，如你所见，小程序会员的JWT中没有携带角色信息，也就是没有RBAC设定，做到后面也只是添加会员等级。网关鉴权只针对系统管理，因为管理端涉及写的接口比较多，小程序 、APP前端大多是读接口，只做是否登录，token是否有效判断
