### ISSUE TITLE
请问为什么带着token请求 /user/me的时候,header里没有playload

### ISSUE THREAD

**Issue by YuhooZhu** [hxrui/youlai-mall#21]
![image](https://user-images.githubusercontent.com/49890582/110089347-f9a5e300-7dd0-11eb-89e6-a05d4f9715f3.png)

**Comment by hxrui** [comment]
@YuhooZhu 请求Header截个图，看Authorization字段的值

**Comment by YuhooZhu** [comment]
![image](https://user-images.githubusercontent.com/49890582/110091529-7fc32900-7dd3-11eb-8afc-c37ea30da09f.png)
是这样用的吗?  谢谢

**Comment by hxrui** [comment]
![image](https://user-images.githubusercontent.com/12759477/110091782-cb75d280-7dd3-11eb-89a0-e300cdbf1b90.png)
前缀Bearer小写

**Comment by hxrui** [comment]
@YuhooZhu 前缀Bearer换成小写bearer
![image](https://user-images.githubusercontent.com/12759477/110091870-e6484700-7dd3-11eb-9aac-7cfb9629d985.png)

**Comment by YuhooZhu** [comment]
没注意这个，Postman默认是大写的， 可以了 ，谢谢老哥
