### ISSUE TITLE
新拉取的项目显示undefined

### ISSUE THREAD

**Issue by chenqiang19** [hxrui/youlai-mall#25]
OrderStatusEnum.java
xThe constructor OrderStatusEnum(int, String) is undefined

**Comment by hxrui** [comment]
![image](https://user-images.githubusercontent.com/12759477/113407206-6c5daa80-93df-11eb-8852-67c2aa0ec26c.png)
看了下启动ok的

**Comment by chenqiang19** [comment]
嗯，谢谢，这个与java jdk的版本有关系
