### ISSUE TITLE
资源服务器配置jwk-set-uri: 'http://localhost:8000/getPublicKey'的问题

### ISSUE THREAD

**Issue by CS-HH** [hxrui/youlai-mall#26]
您好，有个问题想请教一下：
jwk这里完全是写死了。如果生产中auth服务有多个，正好写死的这个崩了，那不是整个系统都不可用了吗？
能不能用注册中心来管理，通过服务名调用呢？
期待您的回复！

**Comment by hxrui** [comment]
http://localhost:9999/youlai-auth/getPublicKey

**Comment by CS-HH** [comment]
就是配成网关自己，然后网关再加个路由映射过去对吗？
