### ISSUE TITLE
public.key这个文件是怎么生成的?

### ISSUE THREAD

**Issue by zxmao** [hxrui/youlai-mall#27]
public.key这个文件是怎么生成的?

**Comment by hxrui** [comment]
keytool -list -rfc --keystore jwt.jks | openssl x509 -inform pem -pubkey
项目新版本文档我最近更新

**Comment by klyang-chinaatech** [comment]
openssl也要安装，
下载地址  http://slproweb.com/products/Win32OpenSSL.html
环境变量path中配置openssl安装路径，如：C:\OpenSSL-Win64\bin
