### ISSUE TITLE
关于修改密码问题

### ISSUE THREAD

**Issue by gzymomo** [hxrui/youlai-mall#3]
如果管理后台用户需要修改密码，是要到auth 里面去加密吗?

**Comment by hxrui** [comment]
不是，管理后台用户修改密码在youlai-admin这里修改就好

**Comment by gzymomo** [comment]
要把 Auth 里面的加密方法在admin 里面也要加一下？

**Comment by hxrui** [comment]
在admin模块引入Spring Security的jar包，使用PasswordEncoder加密就行了，详细如下

```java
@Configuration
public class PasswordEncoderConfig {
    @Bean
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }
}

```

```java
@Autowired
private PasswordEncoder passwordEncoder;
......
SysUser user=new SysUser().setPassword(passwordEncoder.encode(password));
```

**Comment by gzymomo** [comment]
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-crypto</artifactId>
</dependency> 
用他这个就好

**Comment by hxrui** [comment]
> org.springframework.security spring-security-crypto 用他这个就好

哦哦  这个是security加密子模块是吗？
