### ISSUE TITLE
关于Open-Feign转发丢失请求头

### ISSUE THREAD

**Issue by gadfly3173** [hxrui/youlai-mall#32]
部分api接口在处理中需要根据jwt认证头来获取用户id，现在代码中的通过服务名直接调用的操作会导致调用的时候丢失请求头，因此可以将其改为使用网关转发。

示例如下：
原MemberAddressFeignClient.java
https://github.com/hxrui/youlai-mall/blob/bff37cda62dd6796a1b6f8f673dc9721cfcc2507/mall-ums/ums-api/src/main/java/com/youlai/mall/ums/api/MemberAddressFeignClient.java#L11-L26

修改后：
```java
@FeignClient("youlai-gateway")
public interface MemberAddressFeignClient {

    /**
     * 获取地址详情
     */
    @GetMapping("/mall-ums/app-api/v1/addresses/{id}")
    Result<UmsAddress> getById(@PathVariable("id") Long id);


    @GetMapping("/mall-ums/app-api/v1/addresses")
    Result<List<UmsAddress>> list(@RequestParam Long memberId);

}
```

**Comment by hxrui** [comment]
@gadfly3173 赞一个，但是这样玩性能有些损失的。对了有没兴趣一起玩这个项目？

**Comment by gadfly3173** [comment]
> @gadfly3173 赞一个，但是这样玩性能有些损失的。对了有没兴趣一起玩这个项目？

改成feign拦截器的形式发了pr
