### ISSUE TITLE
配置文件更新后不能立即生效

### ISSUE THREAD

**Issue by jl135542** [hxrui/youlai-mall#4]
通过nacos配置列表，编辑修改yaml配置后，发布后不能生效，还是需要重启项目

**Comment by hxrui** [comment]
不知道你具体哪里的配置，我在这篇文章有实验过可以动态刷新，[Spring Cloud实战 | 第三篇：Spring Cloud整合Nacos实现配置中心](https://www.cnblogs.com/haoxianrui/p/13585125.html)。
