### ISSUE TITLE
项目功能报错

### ISSUE THREAD

**Issue by jl135542** [hxrui/youlai-mall#5]
演示项目中多处功能提示报错，如用户管理，点击修改就会报错
![image](https://user-images.githubusercontent.com/34938786/102201301-dc175a80-3f00-11eb-941f-a92bf8bd9a43.png)

**Comment by hxrui** [comment]
抱歉，自己精力有限，目前在不影响整个系统运行情况下，有些页面的增删改查细节没有去做。
