### ISSUE TITLE
关于异常处理取消了HTTP状态也改为异常码的疑问

### ISSUE THREAD

**Issue by gadfly3173** [hxrui/youlai-mall#57]
commit:317c1d7ec6ea69f28e745d53a9dadfaf2da67d82 把用于将HTTP状态码改为400的ResponseStatus注解都注释掉是出于什么考虑呢？axios这个时候如果不能在res里处理的话也可以在error回调里处理的

**Comment by hxrui** [comment]
@gadfly3173 了解了，我把管理端和小程序端都改下。当时为了调试小程序功能就暂先注释了。
